### ISSUE TITLE
How does this package support dnxcore50?

### ISSUE THREAD

**Issue by davidfowl** [serilog/serilog-framework-logging#1]
How does this package support dnxcore50 if serilog itself doesn't?

**Comment by nblumhardt** [comment]
Serilog does; it's a two-assembly package. _Serilog.dll_ is a new-style PLIB, so runs on just about anything modern and seems to be fine on `dnxcore50`. The second assembly containing most of the sinks, _Serilog.FullNetFx.dll_, is .NET 4.5 specific and that's where we need to do some work.

At the time of writing, I think only the `Observers()` and `TextWriter()` sinks will work on core.

I started a filler package with some `dnxcore50` ports at https://github.com/serilog/serilog-dnx-prerelease. It's pretty limited and doesn't help with any downstream sinks, so instead effort should probably go into getting a reorganised package ready for the RTW.
