### ISSUE TITLE
Support for beta7

### ISSUE THREAD

**Issue by csunali** [serilog/serilog-framework-logging#13]
The code that used to work before stopped working all of a sudden. Am I missing something?

```
var logger = new LoggerConfiguration()
    .MinimumLevel.Warning()
    .CreateLogger();

loggerFactory.AddSerilog(logger);
```

Throws:

```
System.TypeLoadException
Method 'Dispose' in type 'Serilog.Framework.Logging.SerilogLoggerProvider' from assembly 'Serilog.Framework.Logging, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at Microsoft.Framework.Logging.SerilogLoggerFactoryExtensions.AddSerilog(ILoggerFactory factory, ILogger logger)
```

**Comment by nblumhardt** [comment]
Hi Coskun;

Did you update any packages between working and non-working code? It'd seem that a package version would need to change for this to happen.

Which ASP.NET version are you running it on - beta5, 6, etc?

Cheers,
Nick

**Comment by csunali** [comment]
Hi Nicholas,

Sorry, my bad that I have not provided any details on versions. It was about 4 AM in the morning when I posted the issue :)

Yes, the code used to work prior to updating the packages. 

I am running the latest beta 7 dev bits. Current `Microsoft.Aspnet.Http.Abstractions` assembly seems to have version `1.0.0-beta7-11813`.

Hope that helps. Otherwise please let me know if I can be of any further assistance in order for you to diagnose the reason of the failure.

**Comment by csunali** [comment]
By the way, the Serilog package has the version `"Serilog.Framework.Logging": "1.0.0-beta-43"`

**Comment by IsaacSee** [comment]
Hi there, juste upgraded to last beta7 to date. 
I ended up with the same exception.

**Comment by nblumhardt** [comment]
Thanks for weighing in. Keeping up to date with ASP.NET is a bit challenging. I'm aiming to push beta6 versions to master and NuGet, and bring the dev branch up to beta7. Working on it now, may be a day or two until everything is done.

**Comment by martinbooth** [comment]
This is probably the only thing which needs to be supported:

https://github.com/aspnet/Logging/issues/99

i.e. in serilog's case, it probably just needs an empty dispose method

**Comment by Asshiah** [comment]
Beta 7 is now out.

This error is still present with Serilog.

**Comment by nblumhardt** [comment]
I've added `Dispose()` and updated the dependency versions in b33c73eaa0d2ee2fec5022f05b5559c724fbba2e - this is now on NuGet.

Can someone using `beta6` please confirm that the upgrade is smooth for them? :-)

Cheers!

**Comment by Asshiah** [comment]
The problem is now gone with beta7^^ Thanks a lot!

**Comment by nblumhardt** [comment]
Excellent :-) Thanks!
