### ISSUE TITLE
Create a branch that tracks the current aspnet dev branches and one that tracks the latest stable (nuget.org)

### ISSUE THREAD

**Issue by davidfowl** [serilog/serilog-framework-logging#2]
In order to keep up with development of ASP.NET 5, i'd recommend 2 branches:
- master - Has the release compatible with the version on NuGet.org (at time of writing http://www.nuget.org/packages/Microsoft.Framework.Logging.Interfaces/1.0.0-beta4)
- dev - This tracks the myget package https://www.myget.org/gallery/aspnetvnext (at time of writing Microsoft.Framework.Logging.Abstractions)

**Comment by nblumhardt** [comment]
Thanks - good suggestion, will do.

**Comment by nblumhardt** [comment]
Done; I've also added a checklist item to get a MyGet feed up for `dev` (would benefit a lot of Serilog packages) here https://github.com/serilog/serilog/issues/447.
