### ISSUE TITLE
Error : "Could not load..."

### ISSUE THREAD

**Issue by StanislavPrusac** [serilog/serilog-framework-logging#20]
1. I have error: 
> "Could not load type 'Microsoft.Framework.Logging.SerilogLoggerFactoryExtensions' from assembly 'Serilog.Framework.Logging, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.":"Microsoft.Framework.Logging.SerilogLoggerFactoryExtensions"

2. I used: 
> "Microsoft.Framework.Logging": "1.0.0-*",
> "Serilog.Framework.Logging": "1.0.0-*",

3. which probably convert to:
> "Microsoft.Framework.Logging": "1.0.0-rc1-15644"
> "Serilog.Framework.Logging": "1.0.0-rc1-final-10071"

4. When I return to: 
> "Microsoft.Framework.Logging": "1.0.0-beta8",
> "Serilog.Framework.Logging": "1.0.0-beta8-10056",

all work correctly.

**Comment by vivanov1410** [comment]
There no `Microsoft.Framework.Logging;`, use `Microsoft.Extensions.Logging;`

**Comment by nblumhardt** [comment]
That's correct - it may be that you need to update your local version of the DNX tools etc. Please let us know if you have any further trouble. Cheers!
