### ISSUE TITLE
Target error installing rc1 on .NET 4.5.2

### ISSUE THREAD

**Issue by ccelebiler** [serilog/serilog-framework-logging#23]
I am using the framework in a .NET 4.5.2 project. When I try to install rc1 (10071) I get the following error:
"Could not install package 'Serilog.Framework.Logging 1.0.0-rc1-final-10071'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."
I tried changing the target to 4.5.1 and 4.5 without success.
The previous beta8 (10065) installs correctly.

**Comment by nblumhardt** [comment]
Hi - I'm not sure what the story is for ASPNET5 and .NET 4.5 - any reason not to use .NET 4.6 here? If we can fix this with a package.json tweak let me know. Cheers!

**Comment by ccelebiler** [comment]
Probably a change between beta8 and rc1 broke the compatibility with .NET 4.5 (btw I tried 4.6 too and it does not work).
I went through the changes history and noticed that "net45" framework was removed from package.json during the upgrade from beta8  to rc1. Could this be the cause of the issue?

**Comment by nblumhardt** [comment]
That would have done it; a bit of an oversight by the looks of things :-s

Looks like _m.e.Logging_ moved forwards from .NET 4.5 to 4.5.1 in RC1; I've updated the package and a new build should be on its way via CI.

Thanks!

**Comment by anthonymiller-simple** [comment]
Cannot install into ASP.Net project for any version. 4.5, 4.5.1 or 4.6.1. Comes up with the following error: Install-Package : Failed to add reference to 'System.Collections.Concurrent'. Please make sure that it is in the Global Assembly Cache.
