### ISSUE TITLE
>= DNX Beta5 compatible nuget package publish

### ISSUE THREAD

**Issue by trevorreeves** [serilog/serilog-framework-logging#6]
This is an easy one :-)

Any chance of publishing the latest as a Nuget package; the current '1.0.0-beta-2' version is dependant on MS beta4 with the now defunct '.Interfaces' package.

It's not currently possible to work on DNX projects >= Beta5, straight out of Nuget at the moment.

Thanks.

**Comment by nblumhardt** [comment]
Will do; thanks!

**Comment by davidpeden3** [comment]
+1

**Comment by nblumhardt** [comment]
On its way in the next day or so :-)

**Comment by nblumhardt** [comment]
This should do it: https://www.nuget.org/packages/Serilog.Framework.Logging/1.0.0-beta-3

@davidpeden3 @trevorreeves only limited testing of the build, if you spot any issues please give me a heads-up :-)

**Comment by nblumhardt** [comment]
(BTW - since you're using this package today - would love any feedback you can provide on #4 - an interesting proposal in there.)
