### ISSUE TITLE
BeginScope does not log message

### ISSUE THREAD

**Issue by trevorreeves** [serilog/serilog-framework-logging#8]
```c#
using (logger.BeginScope("@Foo1 @Foo2 ignored", foo1, foo2))
{
    ...
}
```

This highlights a small discrepancy between the MFL BeginScope signature and the current Serilog implementation, in that BeginScope takes messageFormat and args, implying that you can log a message.  Whereas the Serilog implementation will only honour any properties defined inside the message format, and ignore everything else.

Is it suitable to log the message provided in BeginScope? Of course there can potentially be multiple nested scopes, so 'scope messages' will be different to the rendered message.

Microsoft's sample implementations seem to not do anything on a BeginScope - so maybe it's fine to only partially honour the interface.  It's just unfortunate that the interface is misleading, and makes it a little more complicated to explain to end users.

**Comment by nblumhardt** [comment]
Thanks @trevorreeves for noticing this - as far as I can tell, Serilog is consistent with all the other sample implementations in its behaviour at this point, but it may be an oversight in MFL. Are you able to follow up with a ticket on the aspnet/Logging repository to clarify? Cheers!

**Comment by trevorreeves** [comment]
Raised an issue with MS to get some clarification on this: https://github.com/aspnet/Logging/issues/222

**Comment by trevorreeves** [comment]
OK, so MS have confirmed that the string message is used by a provider (Elm) - it's not an oversight.  So in a way it's like log values in MFL, or destructured objects in Serilog - you have to plug in the right implementation to get all the features the abstraction implies.

Though I think my point was missed that the Serilog provider doesn't currently record the *string message* from the scope state, (as opposed to just the log values, which it does support).  And I'm guessing that not supporting it is fine - my reason for raising it was to be sure it had been considered.

**Comment by nblumhardt** [comment]
Sorry about the slow response - that sounds fine Trevor, thanks for closing the loop :-)

**Comment by masaeedu** [comment]
I don't understand why this issue is closed. Where is the hierarchical logging context data generated by using the `BeginScope` API going, and how do I get it to appear in my Serilog sinks?

**Comment by nblumhardt** [comment]
@masaeedu thanks for the nudge. I've raised #50; I don't think BeginScope will log a message, but attaching a hiearchical scope property for string keys makes sense.

**Comment by MelbourneDeveloper** [comment]
@trevorreeves my naive understanding of BeginScope is that arguments in the param array should get passed to each subsequent Log call after BeginScope is called. So, for example, in the case of Application Insights, each argument in the array would turn up as a customDimension value on the other side in application insights. None of the libraries I've looked at seem to do anything with the arguments passed into the param array with BeginScope. Serilog is no exception. Why don't they log the values? I just want to see them there in the console so I know that Serilog is going something with them.

Is there some implementation where we can Serilog doing something with these values? Sorry if I'm being vague here.
